"""add downloads_num + revenue_num to market_rank_snapshots

Revision ID: afec0ab9235a
Revises: 0001
Create Date: 2026-04-29 14:59:03.352765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afec0ab9235a'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_rank_snapshots', sa.Column('downloads_num', sa.BigInteger(), nullable=True))
    op.add_column('market_rank_snapshots', sa.Column('revenue_num', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_rank_snapshots', 'revenue_num')
    op.drop_column('market_rank_snapshots', 'downloads_num')
    # ### end Alembic commands ###
